import type { Metadata } from "next";
import PendingLink from "@/components/PendingLink";

export const metadata: Metadata = {
  title: "Cookie Policy (EU) | NEST360",
};

// Shell of https://nest360.org/cookie-policy-eu/
// The live policy is generated by the Complianz WordPress plugin (synced with
// cookiedatabase.org) and describes cookies set by the WordPress/Divi site,
// which this Next.js site won't set. Its body text isn't copied here; the
// policy needs to be regenerated for the new site, so only the section
// structure and the services it currently lists are kept as a guide.

const sections = [
  { heading: "1. Introduction", subheadings: [] },
  { heading: "2. What are cookies?", subheadings: [] },
  { heading: "3. What are scripts?", subheadings: [] },
  { heading: "4. What is a web beacon?", subheadings: [] },
  {
    heading: "5. Cookies",
    subheadings: [
      "5.1 Technical or functional cookies",
      "5.2 Statistics cookies",
      "5.3 Marketing/Tracking cookies",
      "5.4 Social media",
    ],
  },
  {
    heading: "6. Placed cookies",
    subheadings: [
      "WordPress",
      "Google reCAPTCHA",
      "Google Analytics",
      "Divi (Elegant Themes)",
      "Google Fonts",
      "Google Maps",
      "Vimeo",
      "YouTube",
      "Facebook",
      "Twitter",
      "LinkedIn",
      "Complianz",
      "Miscellaneous",
    ],
  },
  {
    heading: "7. Consent",
    subheadings: ["7.1 Manage your consent settings"],
  },
  { heading: "8. Enabling/disabling and deleting cookies", subheadings: [] },
  { heading: "9. Your rights with respect to personal data", subheadings: [] },
  { heading: "10. Contact details", subheadings: [] },
];

export default function CookiePolicyPage() {
  return (
    <main>
      <h1>Cookie Policy (EU)</h1>
      <p>
        <strong>
          Policy text must be regenerated for the new site.
        </strong>{" "}
        See the{" "}
        <PendingLink to="https://nest360.org/cookie-policy-eu/">
          current policy on nest360.org
        </PendingLink>
        .
      </p>

      {sections.map((section) => (
        <section key={section.heading}>
          <h2>{section.heading}</h2>
          {section.subheadings.map((subheading) => (
            <h3 key={subheading}>{subheading}</h3>
          ))}
        </section>
      ))}
    </main>
  );
}
